apiVersion: v1
kind: Secret
metadata:
  name: mysql-username
type: Opaque
data:
  username: cm9vdA== 

---  

apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: Opaque
data:
  password: cXdlcnR5dWk=